### ISSUE TITLE
Small typo on homepage "on-premesis"

### ISSUE THREAD

**Issue by dreth** [VeriHash/verihash.github.io#5]
Hi,

There's a small typo on the homepage, "on-premesis", it should be "on-premises"

https://github.com/VeriHash/verihash.github.io/blob/bf740ad9297bafd14aa79e8fb0ddf34474cb32ea/index.html#L88

**Comment by beegmon** [comment]
Nice find and appreciate the call out! Will fix shortly.

**Comment by dnlglsn** [comment]
Thanks @dreth !
